server:
  port: 8080

payments:
  default-service-id: bancolombia
  services-by-id:
    bancolombia:
      base-url: https://test.security.flypass.co/flypass/bancolombia-integration
      connect-timeout: 1s
      read-timeout: 2s
      max-attempts-get: 3
    external:
      base-url: https://example.com/external-payments
      connect-timeout: 1s
      read-timeout: 2s
      max-attempts-get: 2

resilience4j:
  circuitbreaker:
    instances:
      bancolombia:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      external:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
      yuno:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15s
  retry:
    instances:
      bancolombia:
        maxAttempts: 3
        waitDuration: 200ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2.0
        retryExceptions:
          - org.springframework.web.client.RestClientException
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.ResourceAccessException
          - java.net.SocketTimeoutException
        ignoreExceptions:
          - org.springframework.web.client.HttpClientErrorException
      external:
        maxAttempts: 2
        waitDuration: 100ms
        retryExceptions:
          - org.springframework.web.client.RestClientException
        ignoreExceptions:
          - org.springframework.web.client.HttpClientErrorException
      yuno:
        maxAttempts: 2
        waitDuration: 150ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2.0
        retryExceptions:
          - org.springframework.web.client.RestClientException
        ignoreExceptions:
          - org.springframework.web.client.HttpClientErrorException

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.co.flypass.payments.bff: DEBUG
