server:
  port: 8080

payments:
  default-service-id: bancolombia
  services-by-id:
    bancolombia:
      base-url: https://test.security.flypass.co/flypass/bancolombia-integration
      connect-timeout: 1s
      read-timeout: 2s
      max-attempts-get: 3


resilience4j:
  retry:
    instances:
      payments-get:
        maxAttempts: 3
        waitDuration: 200ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2.0
        maxWaitDuration: 2s
        retryExceptions:
          - org.springframework.web.client.RestClientException
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.ResourceAccessException
          - java.net.SocketTimeoutException
        ignoreExceptions:
          - org.springframework.web.client.HttpClientErrorException

logging:
  level:
    root: INFO
    com.co.flypass.payments.bff: DEBUG
